# Generated by Django 3.1.3 on 2023-08-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course_id',
            field=models.ManyToManyField(to='onlinecourse.Course'),
        ),
    ]
