# Generated by Django 3.1.3 on 2023-08-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_question_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course_id',
        ),
    ]
